version: 0.2 
 
phases: 
  install: 
    commands: 
      - apt-get update -y 
      - apt-get install -y build-essential 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Compiling the C++ code... 
      - g++ kplabs.cpp -o kplabs 
  post_build: 
    commands: 
      - echo Build completed on `date` 
artifacts: 
  files: 
    - kplabs 
